version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - "9090:8080"
    depends_on:
      - mysql-container

  mysql-container:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"

    environment:
      MYSQL_DATABASE: QL_ChuyenBay
      MYSQL_USER: root
      MYSQL_PASSWORD: 24683579
      MYSQL_ROOT_PASSWORD: 24683579
